services:
  elastic1:
    container_name: elastic1
    hostname: elastic1
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/elastic1:/usr/share/elasticsearch/data
    healthcheck:
      test:
        ["CMD-SHELL", "curl -s http://localhost:9200 | grep -q 'cluster_name'"]
      interval: 10s
      timeout: 10s
      retries: 120
  api:
    build: .
    ports:
      - "80:80"
